include("steps/Alpha.jl")
include("steps/A.jl")
include("steps/B.jl")
include("steps/C.jl")
include("steps/D.jl")
include("steps/E.jl")
include("steps/F.jl")
include("steps/G.jl")

function stepOmega!(m::Model)
end

function step!(m)
    stepAlpha!(m)
    stepA!(m)
    stepB!(m)
    stepC!(m)
    stepD!(m)
    stepE!(m)
    stepF!(m)
    stepG!(m)
    stepH!(m)
    stepI!(m)
    stepJ!(m)
    stepK!(m)
    stepL!(m)
    stepM!(m)
    stepN!(m)
    stepO!(m)
    stepP!(m)
    stepQ!(m)
    stepOmega!(m)
    display_matrices(m, m.t)
end